version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: anki_mysql_prod
    platform: linux/x86_64
    ports:
      - "3351:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - anki_mysql_data_prod:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: anki_backend_prod
    ports:
      - "5193:5193"
    volumes:
      - ./examples:/app/examples
      - ./backend/resources:/app/src/resources
    env_file:
      - .env.prod
    depends_on:
      - mysql
    restart: on-failure:3
    environment:
      - VIRTUAL_HOST=${API_DOMAIN}
      - VIRTUAL_PORT=5193
      - LETSENCRYPT_HOST=${API_DOMAIN}
    networks:
      - app_network
    healthcheck:
      test: wget --spider -q http://localhost:5193/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://${API_DOMAIN}
    container_name: anki_frontend_prod
    ports:
      - "3123:3123"
    env_file:
      - .env.prod
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}
      - VIRTUAL_PORT=3123
      - LETSENCRYPT_HOST=${FRONTEND_DOMAIN}
    labels:
      - "traefik.frontend.rule=Host:${FRONTEND_DOMAIN}"
      - "traefik.port=3123"
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy.custom_nginx_server_config=location = /favicon.ico { proxy_pass http://frontend:3123/favicon.ico; access_log off; log_not_found off; expires max; }"
    networks:
      - app_network
    healthcheck:
      test: wget --spider -q http://localhost:3123 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  app_network:
    external: true

volumes:
  anki_mysql_data_prod:
