version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - FRONTEND_DOMAIN
      - API_DOMAIN
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql-prod
    expose:
      - "3306"
    env_file:
      - .env.prod
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-prod
    expose:
      - "5193"
    env_file:
      - .env.prod
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-prod
    expose:
      - "3123"
    env_file:
      - .env.prod
    restart: unless-stopped

volumes:
  mysql_data: